AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template to create a new AWS Secret storing credentials for a consumer group of a specific confluent kafka cluster

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CCloud Master credentials
        Parameters:
          - CcloudEmail
          - CcloudPassword

Parameters:
  CcloudEmail:
    Type: String
  CcloudPassword:
    NoEcho: True
    Type: String

Resources:
  KafkaSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/kafka/ccloud/master/${AWS::Region}'
      Description: "Kafka SASL and Schema Registry credentials"
      SecretString: !Sub |
        {
          "email": "${CcloudEmail}",
          "password": "${CcloudPassword}"
        }
